services:
  postgres:
    container_name: "ovara-postgres"
    image: "postgres:15.5"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=ovara