remote-ip := "10.20.89.144"

_default:
    just --list --unsorted

ssh-to-remote-db-in-pallero:
    ssh -N -L 5435:rds-privatelink.ovara.testiopintopolku.fi:5432 pallero-bastion



connect-to-remote-db:
    sshuttle -l 0.0.0.0 -r pallero-bastion {{remote-ip}}/32
