name: setup-next-env
description: 'Setup Next.js environment'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        standalone: true
        run_install: false
        package_json_file: 'ovara-ui/package.json'
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'ovara-ui/.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: ovara-ui/pnpm-lock.yaml
        registry-url: 'https://npm.pkg.github.com'
        scope: '@opetushallitus'
    - uses: actions/cache@v4
      id: node_modules-cache
      with:
        path: ${{ github.workspace }}/ovara-ui/node_modules
        key: ${{ runner.os }}-modules-${{ env.PNPM_NODE_LINKER || 'isolated' }}-${{ hashFiles('ovara-ui/pnpm-lock.yaml') }}
    - name: Cache Next.js
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/ovara-ui/.next/cache
        key: ${{ runner.os }}-nextjs-${{ env.PNPM_NODE_LINKER || 'isolated' }}-${{ hashFiles('ovara-ui/pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', './src/**/*.ts', './src/**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ env.PNPM_NODE_LINKER || 'isolated' }}-${{ hashFiles('ovara-ui/pnpm-lock.yaml') }}-
    - name: Install pnpm dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ovara-ui
        pnpm install
